export const agits = [
  {
    agitName: '모임명1',
    image: 'https://picsum.photos/250/250',
    currentPersonNumber: 13,
    totalPersonNumber: 30,
    introduction: '한줄소개1 한줄소개1 한줄소개1',
    agitSubject: '운동',
    agitInterests: ['격투기', '수영', '등산'],
  },
  {
    agitName: '모임명2',
    image: 'https://picsum.photos/250/250',
    currentPersonNumber: 20,
    totalPersonNumber: 50,
    introduction: '한줄소개2 한줄소개2 한줄소개2',
    agitSubject: '여행',
    agitInterests: ['관광 명소'],
  },
  {
    agitName: '모임명3',
    image: 'https://picsum.photos/250/250',
    currentPersonNumber: 4,
    totalPersonNumber: 100,
    introduction: '한줄소개3 한줄소개3 한줄소개3',
    agitSubject: '게임/오락',
    agitInterests: ['VR/AR', '보드게임'],
  },
];

export const events = [
  {
    eventsId: 1,
    image: 'https://picsum.photos/250/250',
    eventName: '정모이름1',
    eventPlace: '상암동',
    eventDate: '2024-12-08',
    totalPerson: '20',
    currentPerson: '10',
    introduction: '한줄소개1 한줄소개1 한줄소개1',
  },
  {
    eventsId: 2,
    image: 'https://picsum.photos/250/250',
    eventName: '정모이름2',
    eventPlace: '연남동',
    eventDate: '2024-12-31',
    totalPerson: '23',
    currentPerson: '10',
    introduction: '한줄소개2 한줄소개2 한줄소개2',
  },
  {
    eventsId: 3,
    image: 'https://picsum.photos/250/250',
    eventName: '정모이름3',
    eventPlace: '서교동',
    eventDate: '2025-01-25',
    totalPerson: '24',
    currentPerson: '10',
    introduction: '한줄소개3 한줄소개3 한줄소개3',
  },
];
